# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_default_source_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_balanced',
            field=models.BooleanField(default=False, verbose_name='default balanced'),
        ),
    ]
