# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 20:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('categories', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='amount')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'planned'), (2, 'registered'), (3, 'balanced')], default=2)),
                ('transaction_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'withdrawal'), (2, 'deposit'), (3, 'transfer')], verbose_name='transaction type')),
                ('category', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name='category')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_as_destination', to='accounts.Account', verbose_name='destination')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_as_source', to='accounts.Account', verbose_name='source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
    ]
