# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='amount'),
        ),
    ]
