# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='modified_at',
            field=models.DateTimeField(null=True, verbose_name='modified at'),
        ),
    ]
