# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0002_auto_20170528_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_as_destination', to='accounts.Account', verbose_name='destination'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_as_source', to='accounts.Account', verbose_name='source'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('source', 'destination')]),
        ),
    ]
