# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20170605_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modified_at',
            field=models.DateTimeField(verbose_name='modified at'),
        ),
    ]
