# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:56
from __future__ import unicode_literals

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('transactions', '0004_auto_20170528_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='labels',
            field=mptt.fields.TreeManyToManyField(to='labels.Label', verbose_name='labels'),
        ),
    ]
