# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20170606_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balanced',
            field=models.BooleanField(default=False, verbose_name='balanced'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='balanced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='balanced at'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='datetime'),
        ),
    ]
