# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'planned'), (2, 'registered'), (3, 'balanced')], default=2),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'withdrawal'), (2, 'deposit')], default=1),
            preserve_default=False,
        ),
    ]
