# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 19:27
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20170606_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name='category'),
        ),
    ]
