# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20170529_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'withdrawal'), (2, 'deposit'), (3, 'transfer')]),
        ),
    ]
