# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 21:50
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_label_transaction_type'),
        ('transactions', '0007_auto_20170529_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='labels',
        ),
        migrations.AddField(
            model_name='transaction',
            name='label',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='labels.Label', verbose_name='label'),
            preserve_default=False,
        ),
    ]
