# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20170529_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='label',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labels.Label', verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'balance'), (1, 'withdrawal'), (2, 'deposit'), (3, 'transfer')], default=1),
        ),
    ]
