# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 21:02
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transaction_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags'),
        ),
    ]
