# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20170603_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_as_destination', to='accounts.Account', verbose_name='destination'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_as_source', to='accounts.Account', verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'withdrawal'), (2, 'deposit'), (3, 'transfer')], verbose_name='transaction type'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([]),
        ),
    ]
