# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20170607_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='import_hash',
            field=models.CharField(blank=True, max_length=255, verbose_name='import hash'),
        ),
    ]
