# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_transaction_import_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='import_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='import hash'),
        ),
    ]
