# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'withdrawal'), (2, 'deposit')], default=1),
            preserve_default=False,
        ),
    ]
