# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance_planned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='balance planned'),
        ),
        migrations.AddField(
            model_name='account',
            name='balance_registered',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='balance registered'),
        ),
    ]
