# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='balance'),
        ),
    ]
