# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170613_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['order', '-uses'], 'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
    ]
