# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20171101_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='account number'),
        ),
    ]
