# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='account number'),
        ),
    ]
